// <auto-generated />
using System;
using App1.Spot.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App1.Spot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190622131822_spotinit")]
    partial class spotinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App1.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("ImageUrl");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<string>("Surname");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("App1.Models.PlayerSpot", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<int>("SpotId");

                    b.HasKey("PlayerId", "SpotId");

                    b.HasIndex("SpotId");

                    b.ToTable("PlayerSpot");
                });

            modelBuilder.Entity("App1.Spot.Data.Entities.Spot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.Property<DateTime?>("LastModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("ShortDescription");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Spot");
                });

            modelBuilder.Entity("App1.Models.PlayerSpot", b =>
                {
                    b.HasOne("App1.Models.Player", "Player")
                        .WithMany("PlayerSpots")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("App1.Spot.Data.Entities.Spot", "Spot")
                        .WithMany("PlayerSpots")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
